services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
    command: poetry run web

  worker:
    build:
      context: .
    command: poetry run worker --docker
  service-mock:
    build:
      context: .
    ports:
      - "5050:5050"
    command: poetry run service-mock --port 5050 --host 0.0.0.0