services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
    command: poetry run web
  worker:
    build:
      context: .
    command: poetry run worker --docker
  service-product:
    build:
      context: .
    ports:
      - "5555:5555"
    command: poetry run service-product --port 5555 --host 0.0.0.0 --random-failures