services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
    command: poetry run web

  worker:
    build:
      context: .
    command: poetry run worker --docker