services:
  webserver:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  worker:
    build:
      context: .
    command: poetry run worker --docker